-- [STR_ARANAP]_Misc
-- Author: Strudeler
-- DateCreated: 5/9/2022 2:48:34 PM
--------------------------------------------------------------
/*	ARAGON ALFONSO V/I THE MAGNANIMOUS DE TRASTAMARA | LOADING INFO		*/
INSERT INTO	LoadingInfo 
			(LeaderType,													BackgroundImage,																ForegroundImage,														PlayDawnOfManAudio)
	VALUES	('LEADER_STR_ARAGON_ALFONSO_V_I_THE_MAGNANIMOUS_DE_TRASTAMARA',	'LEADER_STR_ARAGON_ALFONSO_V_I_THE_MAGNANIMOUS_DE_TRASTAMARA_LOADING_SCREEN',	'LEADER_STR_ARAGON_ALFONSO_V_I_THE_MAGNANIMOUS_DE_TRASTAMARA_NEUTRAL',	0);

/*	ARAGON ALFONSO V/I THE MAGNANIMOUS DE TRASTAMARA | DIPLOMACY SCREEN	*/
INSERT INTO DiplomacyInfo
			(Type,															BackgroundImage)
	VALUES	('LEADER_STR_ARAGON_ALFONSO_V_I_THE_MAGNANIMOUS_DE_TRASTAMARA',	'STR_ARAGON_ALFONSO_V_I_THE_MAGNANIMOUS_DE_TRASTAMARA_COMPOSITE');

/*	NAPLES ALFONSO V/I THE MAGNANIMOUS DE TRASTAMARA | LOADING INFO		*/
INSERT INTO	LoadingInfo 
			(LeaderType,													BackgroundImage,																ForegroundImage,														PlayDawnOfManAudio)
	VALUES	('LEADER_STR_NAPLES_ALFONSO_V_I_THE_MAGNANIMOUS_DE_TRASTAMARA',	'LEADER_STR_NAPLES_ALFONSO_V_I_THE_MAGNANIMOUS_DE_TRASTAMARA_LOADING_SCREEN',	'LEADER_STR_NAPLES_ALFONSO_V_I_THE_MAGNANIMOUS_DE_TRASTAMARA_NEUTRAL',	0);

/*	NAPLES ALFONSO V/I THE MAGNANIMOUS DE TRASTAMARA | DIPLOMACY SCREEN	*/
INSERT INTO DiplomacyInfo
			(Type,															BackgroundImage)
	VALUES	('LEADER_STR_NAPLES_ALFONSO_V_I_THE_MAGNANIMOUS_DE_TRASTAMARA',	'STR_NAPLES_ALFONSO_V_I_THE_MAGNANIMOUS_DE_TRASTAMARA_COMPOSITE');