-- [STR_ARANAP]_Colours
-- Author: Strudeler
-- DateCreated: 5/9/2022 2:46:28 PM
--------------------------------------------------------------
/*	ARAGON ALFONSO V/I THE MAGNANIMOUS DE TRASTAMARA | COLOURS	*/
INSERT INTO	Colors
			(Type,								Color)
	VALUES	('COLOR_STR_ARAGON_A_PRIMARY',		'252,221,10,255'),
			('COLOR_STR_ARAGON_A_SECONDARY',	'218,19,27,255'),

			('COLOR_STR_ARAGON_B_PRIMARY',		'218,19,27,255'),
			('COLOR_STR_ARAGON_B_SECONDARY',	'252,221,10,255'),

			('COLOR_STR_ARAGON_C_PRIMARY',		'0,11,76,255'),
			('COLOR_STR_ARAGON_C_SECONDARY',	'208,109,255,255'),

			('COLOR_STR_ARAGON_D_PRIMARY',		'208,109,255,255'),
			('COLOR_STR_ARAGON_D_SECONDARY',	'0,11,76,255');

INSERT INTO PlayerColors
			(Type,															Usage,		PrimaryColor, 					SecondaryColor,					Alt1PrimaryColor,				Alt1SecondaryColor,				Alt2PrimaryColor,				Alt2SecondaryColor,				Alt3PrimaryColor,				Alt3SecondaryColor)
	VALUES	('LEADER_STR_ARAGON_ALFONSO_V_I_THE_MAGNANIMOUS_DE_TRASTAMARA',	'Unique',	'COLOR_STR_ARAGON_A_PRIMARY',	'COLOR_STR_ARAGON_A_SECONDARY',	'COLOR_STR_ARAGON_B_PRIMARY',	'COLOR_STR_ARAGON_B_SECONDARY',	'COLOR_STR_ARAGON_C_PRIMARY',	'COLOR_STR_ARAGON_C_SECONDARY',	'COLOR_STR_ARAGON_D_PRIMARY',	'COLOR_STR_ARAGON_D_SECONDARY');

/*	NAPLES ALFONSO V/I THE MAGNANIMOUS DE TRASTAMARA | COLOURS	*/
INSERT INTO	Colors
			(Type,								Color)
	VALUES	('COLOR_STR_NAPLES_A_PRIMARY',		'208,109,255,255'),
			('COLOR_STR_NAPLES_A_SECONDARY',	'0,11,76,255'),

			('COLOR_STR_NAPLES_B_PRIMARY',		'0,11,76,255'),
			('COLOR_STR_NAPLES_B_SECONDARY',	'208,109,255,255'),

			('COLOR_STR_NAPLES_C_PRIMARY',		'218,19,27,255'),
			('COLOR_STR_NAPLES_C_SECONDARY',	'252,221,10,255'),

			('COLOR_STR_NAPLES_D_PRIMARY',		'252,221,10,255'),
			('COLOR_STR_NAPLES_D_SECONDARY',	'218,19,27,255');

INSERT INTO PlayerColors
			(Type,															Usage,		PrimaryColor, 					SecondaryColor,					Alt1PrimaryColor,				Alt1SecondaryColor,				Alt2PrimaryColor,				Alt2SecondaryColor,				Alt3PrimaryColor,				Alt3SecondaryColor)
	VALUES	('LEADER_STR_NAPLES_ALFONSO_V_I_THE_MAGNANIMOUS_DE_TRASTAMARA',	'Unique',	'COLOR_STR_NAPLES_A_PRIMARY',	'COLOR_STR_NAPLES_A_SECONDARY',	'COLOR_STR_NAPLES_B_PRIMARY',	'COLOR_STR_NAPLES_B_SECONDARY',	'COLOR_STR_NAPLES_C_PRIMARY',	'COLOR_STR_NAPLES_C_SECONDARY',	'COLOR_STR_NAPLES_D_PRIMARY',	'COLOR_STR_NAPLES_D_SECONDARY');