-- [STR_ARANAP]_Maps
-- Author: Strudeler
-- DateCreated: 1/10/2023 1:01:25 AM
--------------------------------------------------------------
/*	ARAGON/NAPLES TSL	*/
CREATE TABLE IF NOT EXISTS StartPosition (MapName TEXT, Civilization TEXT, Leader TEXT, X INT default 0, Y INT default 0);

INSERT INTO StartPosition
			(MapName,				Civilization,				Leader,															X,	Y)
	VALUES	('GiantEarth',			'CIVILIZATION_STR_ARAGON',	'LEADER_STR_ARAGON_ALFONSO_V_I_THE_MAGNANIMOUS_DE_TRASTAMARA',	10,	59),
			('GreatestEarthMap',	'CIVILIZATION_STR_ARAGON',	'LEADER_STR_ARAGON_ALFONSO_V_I_THE_MAGNANIMOUS_DE_TRASTAMARA',	40,	40),
			('LargeEurope',			'CIVILIZATION_STR_ARAGON',	'LEADER_STR_ARAGON_ALFONSO_V_I_THE_MAGNANIMOUS_DE_TRASTAMARA',	23,	32),
			('PlayEuropeAgain',		'CIVILIZATION_STR_ARAGON',	'LEADER_STR_ARAGON_ALFONSO_V_I_THE_MAGNANIMOUS_DE_TRASTAMARA',	24,	40),

			('GiantEarth',			'CIVILIZATION_STR_NAPLES',	'LEADER_STR_NAPLES_ALFONSO_V_I_THE_MAGNANIMOUS_DE_TRASTAMARA',	21,	57),
			('GreatestEarthMap',	'CIVILIZATION_STR_NAPLES',	'LEADER_STR_NAPLES_ALFONSO_V_I_THE_MAGNANIMOUS_DE_TRASTAMARA',	51,	41),
			('LargeEurope',			'CIVILIZATION_STR_NAPLES',	'LEADER_STR_NAPLES_ALFONSO_V_I_THE_MAGNANIMOUS_DE_TRASTAMARA',	38,	29),
			('PlayEuropeAgain',		'CIVILIZATION_STR_NAPLES',	'LEADER_STR_NAPLES_ALFONSO_V_I_THE_MAGNANIMOUS_DE_TRASTAMARA',	46,	32);