INSERT INTO IconTextureAtlases
		(Name,											IconSize,	IconsPerRow,	IconsPerColumn,	Filename)
VALUES	('ICON_ATLAS_PHANTA_PAVILION_PRINCE_TENG',		32,			1,				1,				'ICON_BUILDING_PHANTA_PAVILION_PRINCE_TENG_32.dds'),
		('ICON_ATLAS_PHANTA_PAVILION_PRINCE_TENG',		38,			1,				1,				'ICON_BUILDING_PHANTA_PAVILION_PRINCE_TENG_38.dds'),
		('ICON_ATLAS_PHANTA_PAVILION_PRINCE_TENG',		50,			1,				1,				'ICON_BUILDING_PHANTA_PAVILION_PRINCE_TENG_50.dds'),
		('ICON_ATLAS_PHANTA_PAVILION_PRINCE_TENG',		80,			1,				1,				'ICON_BUILDING_PHANTA_PAVILION_PRINCE_TENG_80.dds'),
		('ICON_ATLAS_PHANTA_PAVILION_PRINCE_TENG',		128,		1,				1,				'ICON_BUILDING_PHANTA_PAVILION_PRINCE_TENG_128.dds'),
		('ICON_ATLAS_PHANTA_PAVILION_PRINCE_TENG',		256,		1,				1,				'ICON_BUILDING_PHANTA_PAVILION_PRINCE_TENG_256.dds');
--------------------------------------------------------------

-- IconDefinitions
--------------------------------------------------------------
INSERT OR REPLACE INTO IconDefinitions
		(Name,												Atlas,										'Index')
VALUES	('ICON_BUILDING_PHANTA_PAVILION_PRINCE_TENG',		'ICON_ATLAS_PHANTA_PAVILION_PRINCE_TENG',	0),
		('ICON_BUILDING_PHANTA_PAVILION_PRINCE_TENG_FOW',	'ICON_ATLAS_PHANTA_PAVILION_PRINCE_TENG',	0),
		('ICON_GREATWORK_PHANTA_CHEN_ZIANG_1',				'ICON_ATLAS_GREATWORKS',					0),
		('ICON_GREATWORK_PHANTA_CHEN_ZIANG_2',				'ICON_ATLAS_GREATWORKS',					0),
		('ICON_GREATWORK_PHANTA_HE_ZHIZHANG_1',				'ICON_ATLAS_GREATWORKS',					0),
		('ICON_GREATWORK_PHANTA_HE_ZHIZHANG_2',				'ICON_ATLAS_GREATWORKS',					0),
		('ICON_GREATWORK_PHANTA_LUO_BINWANG_1',				'ICON_ATLAS_GREATWORKS',					0),
		('ICON_GREATWORK_PHANTA_LUO_BINWANG_2',				'ICON_ATLAS_GREATWORKS',					0),
		('ICON_GREATWORK_PHANTA_LU_ZHAOLIN_1',				'ICON_ATLAS_GREATWORKS',					0),
		('ICON_GREATWORK_PHANTA_LU_ZHAOLIN_2',				'ICON_ATLAS_GREATWORKS',					0),
		('ICON_GREATWORK_PHANTA_WANG_BO_1',					'ICON_ATLAS_GREATWORKS',					0),
		('ICON_GREATWORK_PHANTA_WANG_BO_2',					'ICON_ATLAS_GREATWORKS',					0),
		('ICON_GREATWORK_PHANTA_YANG_JIONG_1',				'ICON_ATLAS_GREATWORKS',					0),
		('ICON_GREATWORK_PHANTA_YANG_JIONG_2',				'ICON_ATLAS_GREATWORKS',					0);
--------------------------------------------------------------