-- Port Lime - K Ataturk - GameText
-- Author: Lime
-- DateCreated: 6/12/2023 9:09:57 PM
--------------------------------------------------------------
INSERT OR REPLACE INTO LocalizedText
		(Language, Tag,					Text)
VALUES	("en_US", "LOC_LEADER_LIME_TURKEY_K_ATATURK_NAME",
		"Kemal Atatürk"),
		("en_US","LOC_LOADING_INFO_LEADER_LIME_TURKEY_K_ATATURK",  
		"Turkey stands at a crossroads, Mustafa Kemal, and has chosen you to lead. Protect your people from oppressors as you teach them science and culture. Set your generals to battle invader and ignorance alike, as you build a nation that will stand the test of time. Take Turkey by the hand, Mustafa Kemal Atatürk, and lead the Turks into an enlightened future. They deserve one last, best hero."),
		("en_US",
		"LOC_PEDIA_LEADERS_PAGE_LEADER_LIME_TURKEY_K_ATATURK_QUOTE",
		"If one day, my words are against science, choose science.");

INSERT OR REPLACE INTO LocalizedText
		(Language, Tag,					Text)
VALUES	("en_US", "LOC_TRAIT_LEADER_LIME_TURKEY_K_ATATURK_HERO_NAME",  
		"Hero of Anafartalar"),
		("en_US", "LOC_TRAIT_LEADER_LIME_TURKEY_K_ATATURK_HERO_DESC",
		"Great Generals recruited during wars gain an extra charge. Gain a [ICON_Governor] Governor title when a Great General is fully expended during peacetime.");

INSERT OR REPLACE INTO LocalizedText
		(Language, Tag,					Text)
VALUES	("en_US",																
		"LOC_PEDIA_LEADERS_PAGE_LEADER_LIME_TURKEY_K_ATATURK_TITLE",							
		"Mustafa Kemal Atatürk"),
		("en_US",
		"LOC_PEDIA_LEADERS_PAGE_LEADER_LIME_TURKEY_K_ATATURK_SUBTITLE",
		"Father of the Turks");

INSERT OR REPLACE INTO LocalizedText
		(Language, Tag,					Text)
VALUES	("en_US", 
		"LOC_PEDIA_LEADERS_PAGE_LEADER_LIME_TURKEY_K_ATATURK_CHAPTER_CAPSULE_BODY",
		"Kemal Atatürk relies very heavily on his staff of generals, which he appoints into governing his nation. By governing Turkey and its many farms, it results in a very flexible game."),
		("en_US", 
		"LOC_PEDIA_LEADERS_PAGE_LEADER_LIME_TURKEY_K_ATATURK_CHAPTER_DETAILED_BODY",
		"Turkey's gameplay focuses primarily on Encampments, Campuses, Theatres, and Farms. Surrounding the three aforementioned districts with farms will result in bursts of science and culture - the encampment in particular helping make up for a lack of either yield. For most of this game, the bursts will come from constructing buildings, though don't forget to use projects to build up a good staff of Generals that Kemal Atatürk can turn into governors. Make sure you build Turkish population high so you can move into any number of victories. Towards the end of the game, projects will be your bread and butter, and the Düzenli Ordu will help in those late-game crises and potential attacks from enemies.");
		
INSERT OR REPLACE INTO LocalizedText
		(Language, Tag,					Text)
VALUES	("en_US",  "LOC_PEDIA_LEADERS_PAGE_LEADER_LIME_TURKEY_K_ATATURK_CHAPTER_HISTORY_PARA_1",
		"Mustafa Kemal Atatürk - a name which many laud and many disdain - was a Field Marshal, Revolutionary, Statesman, Author, Geometry Textbook Writer, Reformer, Founding Father, Benevolent Dictator, Alcoholic, and Hero of the Republic of Turkey. His career was characterized by inspiring resolve to do what must be done, a penchant for snatching victory from the jaws of defeat, and an inability to leave anything to chance. He is, perhaps, one of the most influential figures of the early 20th century."),
		("en_US",  "LOC_PEDIA_LEADERS_PAGE_LEADER_LIME_TURKEY_K_ATATURK_CHAPTER_HISTORY_PARA_2",
		"Like many lionized figures of history, his origins have been heavily mythologized and are largely unknown. He was born at some point in 1881, to middle-class Turkish parents (or perhaps Albanian, or perhaps Jewish, or perhaps Yörük, or perhaps Bulgarian) in Ottoman Selanik. He was born simply as Mustafa. He had some siblings, but all but one died before their childhood. He briefly and reluctantly attended a religious school at the behest of his mother, but his father, an Ottoman military officer, ultimately sent him to a more secular school. When he was seven, his father died, and so did the main source of their income. His mother wanted him to become a tradesman. Instead, he signed up for the Selanik Military School, then attended Ottoman Military High School in Monastir (now Bitola, Macedon), and finally the Ottoman Military Academy in Konstantiniyye. Here is where he got the name Kemal, meaning perfection, partially to denote his perfectionist tendencies but mostly to differentiate him from the other Mustafa in his class. He finally graduated from the Ottoman Military College as well in 1905."),
		("en_US",  "LOC_PEDIA_LEADERS_PAGE_LEADER_LIME_TURKEY_K_ATATURK_CHAPTER_HISTORY_PARA_3",
		"He was then almost immediately arrested."),
		("en_US",  "LOC_PEDIA_LEADERS_PAGE_LEADER_LIME_TURKEY_K_ATATURK_CHAPTER_HISTORY_PARA_4",
		"Evidently during his military education he had become a fervent anti-monarchist and secularist, and generally a critic of existing power structures. Such as Sultan Abdulhamid (whom he helped to overthrow in the Young Turk Revolution in 1908) and the Committee of Union and Progress (it was none of those words) that he was ostensibly a part of (until he left, as well as severing ties with the Young Turks as a whole, after disagreeing with them constantly). Though he continued to be a critic, he was one of the best officers the Ottomans had in an increasingly desperate situation, and so he rose through the ranks and cycled through postings swiftly, though almost all of those postings ended up being somewhere currently at risk, and more importantly away from here!"),
		("en_US",  "LOC_PEDIA_LEADERS_PAGE_LEADER_LIME_TURKEY_K_ATATURK_CHAPTER_HISTORY_PARA_5",
		"His first exposure to conflict beyond suppressing revolts came when he volunteered to fight in the Italo-Turkish war in Libya. Though outnumbered and outclassed (this will be repeated many times. Largely because the Ottomans were having a really, really bad time), he managed to repel Italian forces surprisingly well. It was only when he was recalled to fight in the Balkan wars that the Ottomans promptly ceded Libya in the Treaty of Ouchy (heh) after getting their asses handed to them once Kemal Pasha (as he was now known) was gone."),
		("en_US",  "LOC_PEDIA_LEADERS_PAGE_LEADER_LIME_TURKEY_K_ATATURK_CHAPTER_HISTORY_PARA_6",
		"The Ottomans had mixed success during the Balkan wars, but Kemal Pasha's record remained spotless. He was appointed as the Ottoman Military Attache in the Balkans, and promoted yet again. He met the daughter of a Bulgarian General he fought against in the war, and they began to secretly date and fell in love. Twice he asked the general for her daughter's hand in marriage - once in 1913, and once during the first world war in 1915. Both times he was refused, and he had sadness for the rest of his life."),
		("en_US",  "LOC_PEDIA_LEADERS_PAGE_LEADER_LIME_TURKEY_K_ATATURK_CHAPTER_HISTORY_PARA_7",
		"But his career was far from over. The Ottomans had entered into the first world war, and it was not going well. German and Austrian generals on loan were failing them. But Kemal Atatürk correctly anticipated that the British, under one Winston Churchill, would launch a surprise to seize the Turkish Straits, take Konstantiniyye, and create a supply line for Russia. He managed to repel the initial assault and hold the line for grueling months, inspiring the soldiers to do the impossible: hold off the British empire. The only successful part of the British offensive was its retreat, and Kemal Pasha was rewarded for his valor, now deemed the Hero of Anafartalar, by being shipped off to another front in the war. He managed to repel Russian offensives, and not once during the war did he ever lose a battle, but he also often clashed with leadership, especially the German General Otto Liman von Sanders or the Grand Vizier Talaat Pasha. His opinions, though usually correct, earned him the dubious honor of accompanying the crown prince and future sultan to meet with other leaders of the Triple Alliance... where he told Kaiser Wilhelm II, personally, that he would lose the war."),
		("en_US",  "LOC_PEDIA_LEADERS_PAGE_LEADER_LIME_TURKEY_K_ATATURK_CHAPTER_HISTORY_PARA_8",
		"It was during this time that the Armenian, Greek, and Assyrian Genocides were taking place. To this day, the Turkish Government denies that the atrocities that took place constitute genocide (largely for political reasons related to reparations, especially land reparations, but also because the last guy who brought up Genocide Recognition and Reparations was assassinated), and the Armenian and Greek governments continue to insist that not only they occurred (which they did), but that Mustafa Kemal Atatürk was involved. For the Ottoman phase of the atrocities, Kemal Pasha was busy trying to keep the country from collapsing and was not involved with the CUP's genocides, and in fact openly disparaged the CUP, the genocides, and the Three Pashas as being stupid ruinous maniacs, but it gets more complicated later. We'll get to that."),
		("en_US",  "LOC_PEDIA_LEADERS_PAGE_LEADER_LIME_TURKEY_K_ATATURK_CHAPTER_HISTORY_PARA_9",
		"Nevertheless, his last action during the first world war was organizing Ottoman retreats out of territories before he was finally recalled to Konstantiniyye, now occupied by Allied Forces. For the period from the Armistice of Mudros to mid 1920, he worked for the Ottoman government. But then the Allies tried to partition the nation and occupied both Konstantiniyye and Smyrna, the two largest cities. Former military officers were now gathering in Samsun, and revolution was fomenting. The new puppet Sultan Mehmet VI, who would soon sign away the country, ordered him to go to Samsun and bring them all in order. And so Kemal Pasha did."),
		("en_US",  "LOC_PEDIA_LEADERS_PAGE_LEADER_LIME_TURKEY_K_ATATURK_CHAPTER_HISTORY_PARA_10",
		"By joining them."),
		("en_US",  "LOC_PEDIA_LEADERS_PAGE_LEADER_LIME_TURKEY_K_ATATURK_CHAPTER_HISTORY_PARA_11",
		"He reorganized the Ottoman officers and military into the new Turkish National Movement, and the Ottoman government once again issued a warrant for his arrest. Except then Atatürk's revolutionary party overwhelmingly won the election in the Ottoman Parliament. The British, annoyed, dissolved the Ottoman Parliament in favor of the Sultan just commanding whatever the British told him to do. The Sultan signed the Treaty of Sevrés, which would formally partition Turkey, and Kemal Pasha's parliament in Ankara - the Grand National Assembly, of which Kemal Pasha was the speaker - declared it illegal, and also declared war on the Sultan specifically. The Ottoman government in Konstantiniyye (read: the British Government acting through Constantinople) declared that Kemal Pasha would be given the death penalty, but also admitted that they had no real ability to carry out the sentence yet. So, the Ottoman forces propped up by Allied governments invaded, as well as the armies of Greece and Armenia, who had been promised a slice of Turkey. Except some of these Allies had been promised the same slices. Greece had decided that parts of the Italian mandate belonged to them, Armenian claims (that themselves had only fallen to them after the United States decided that they actually weren't all that interested in a mandate) overlapped with French territories, the Kurds could not help but notice that they'd ended up getting exactly nothing, and Britain was so tired out by the disastrous Gallipoli campaign and the fatigues of the first World War that they weren't going to expend much effort on continuing the Great War in Anatolia. So 1919 grew into a brouhaha, as that is exactly what happened."),
		("en_US",  "LOC_PEDIA_LEADERS_PAGE_LEADER_LIME_TURKEY_K_ATATURK_CHAPTER_HISTORY_PARA_12",
		"The following war was marked by three things: the nearly-hilarious miscommunication between the Allies, a somewhat-constant stream of atrocities (mostly conducted by Turks but some, out of vengeance, conducted by the invading forces), and one triumph after another for Kemal Pasha's armies. First, he defeated the French forces to the south as he courted Soviet Aid. The Soviets and Turks ended up partitioning Armenia, putting an end to that front, having had just enough time in forestalling the Greek assault against Ankara that they were able to turn against them at the Battle of Sakarya, soundly force them into full retreat at the Battle of Dumlupınar, and finally push them into the Sea at Smyrna. The Great Fire of Smyrna on 9 September 1922 was one last bloody atrocity to close out the first world war - but Kemal Pasha had done it. The Country was saved."),
		("en_US",  "LOC_PEDIA_LEADERS_PAGE_LEADER_LIME_TURKEY_K_ATATURK_CHAPTER_HISTORY_PARA_13",
		"The subsequent negotiations saw the Turks give up none of what they decided was vital to their sovereignty and security - all of Anatolia was returned to them, forming much of the borders of Modern Turkey (the Hatay Province was added a few years later under dubious circumstances and election rigging). All the capitulations that the Ottoman State had signed over the centuries were rejected and removed. Control of the Turkish Straits was returned to Turkey, and is in the present day governed by a series of maddeningly vague international treaties called the Montreux Conventions. And on 29 October 1923, the Republic of Turkey was formally declared."),
		("en_US",  "LOC_PEDIA_LEADERS_PAGE_LEADER_LIME_TURKEY_K_ATATURK_CHAPTER_HISTORY_PARA_14",
		"The Turks had very little idea what vision Kemal actually had for the country."),
		("en_US",  "LOC_PEDIA_LEADERS_PAGE_LEADER_LIME_TURKEY_K_ATATURK_CHAPTER_HISTORY_PARA_15",
		"They were under the impression that Field Marshall Kemal would simply Make Turkey Great Again out of his own brilliance. He used his military credentials and status of national hero and golden son to push through a series of sweeping reforms, reshaping the society itself. These reforms were based around the six principles of his ideology of Kemalism: that nationalism held a country together, that a state should control the church rather than the other way around, that a government fundamentally derives its sovereignty from its people, and that science and reason should govern a society. The country was remade into a representative democracy with all trappings of the religious government of the Ottomans forcibly and swiftly removed, the caliphate formally abolished, and the old sultan stripped of all possessions, titles, and citizenship before being exiled for good measure. Turkey was equipped with a large government and a very highly military character. Fresh government services, legal codes, and penal codes were introduced, and the education system completely overhauled right down to the alphabet. But he had his authoritarian streak as well: Turkey was under one party rule for the entirety of his life, religious clothing was completely banned, and in 1927 in the name of preventing the rise of dangerous ideologies (communism, fascism, and the like) there was a series of mass arrests."),
		("en_US",  "LOC_PEDIA_LEADERS_PAGE_LEADER_LIME_TURKEY_K_ATATURK_CHAPTER_HISTORY_PARA_16",
		"His presidency paddled on through the 20s and 30s - with the Surname Law, he was finally given the name most now refer to him as: Atatürk, the Father of the Turks. These years progressed mostly in his efforts for reform and education, even writing textbooks and personally teaching the people himself, for both men and women. Atatürk put special emphasis on women's rights, and one of the many war orphans he adopted would become the world's first female fighter pilot."),
		("en_US",  "LOC_PEDIA_LEADERS_PAGE_LEADER_LIME_TURKEY_K_ATATURK_CHAPTER_HISTORY_PARA_17",
		"All this put together was a comprehensive reform of all of Turkish society: social, political, civic, religious, economic, scientific, religious, cultural, and diplomatic. On that note - he stabilized relationships with all the countries he previously led war after war against, and put together an actual Alliance with Greece (for which he would win the Nobel Peace Prize). Inspiring similar (and far less successful) reforms in Iran and Afghanistan, his successes kept piling up. Personally, he was an indefatigable man - all five-foot-five of him, that smoked several packs and drank a whole liter of raki each day, with little sleep. These years whirled by, and his personal life was kept mostly secret (though largely suffered for it). During the 30s, the man seemed to turn himself solely over to the State."),
		("en_US",  "LOC_PEDIA_LEADERS_PAGE_LEADER_LIME_TURKEY_K_ATATURK_CHAPTER_HISTORY_PARA_18",
		"Until finally, he died. No man lives forever, and at last K. Atatürk died in 1938 at the age of 57, his legacy complete as a complex figure and a Turkish hero. His face is universally known to the Turkish people and the subject of much chagrin of modders attempted to capture his likeness to the exacting standards of Turkish gamers. His military and political accomplishments have no blemish, and he was almost universally adored (at least until recently, when more light has been shown on the war crimes he presided over). He is interred today in the mausoleum of Anıtkabir in Ankara. He was without a doubt a dictator, but the best kind. And to most, he was a hero.");